name: Generate PDF with Open Journals PDF Generator

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  paper:
    runs-on: ubuntu-latest
    name: Paper Draft
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install LaTeX
        run: |
          sudo apt-get update
          sudo apt-get install -y --no-install-recommends \
            texlive-latex-base \
            texlive-fonts-recommended \
            texlive-fonts-extra \
            texlive-latex-extra \
            texlive-xetex \
            texlive-luatex \
            texlive-science \
            texlive-lang-portuguese \
            latexmk \
            lmodern

      - name: Build draft PDF
        uses: openjournals/openjournals-draft-action@master
        with:
          journal: joss
          paper-path: paper.md

      - name: Upload PDF
        uses: actions/upload-artifact@v3
        with:
          name: paper
          path: capesData-paper.pdf
